name: On-review build

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [repo-updated]  # Custom event type you will send

jobs:
  On-review-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install repo tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Set up Repo URL to use HTTPS
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"

      - name: Repo Init and Sync
        run: |
          mkdir -p workspace
          cd workspace
          echo "Initializing repo with manifest from https://github.com/jari-creator/manifest.git"
          repo init -u https://github.com/jari-creator/manifest.git -b main -m default.xml
          echo "Syncing repos"
          repo sync

      - name: List Synced Folders
        run: |
          cd workspace
          ls -l

      - name: Build Android
        run: |
          echo "Build successful"

      # Identify Triggering Repository
      - name: Identify Triggering Repository
        run: |
          if [[ "$GITHUB_EVENT_NAME" == "push" ]]; then
            echo "This build was triggered by a push to $GITHUB_REPOSITORY"
          elif [[ "$GITHUB_EVENT_NAME" == "repository_dispatch" ]]; then
            TRIGGER_REPO=$(jq -r '.client_payload.repository' < $GITHUB_EVENT_PATH)
            echo "This build was triggered by a repository dispatch from $TRIGGER_REPO"
          else
            echo "Unknown trigger event: $GITHUB_EVENT_NAME"
          fi
