name: On-review build

on:
  repository_dispatch:
    types: [repo-updated]  # Custom event type you will send

jobs:
  On-review-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.client_payload.repository }}
          ref: ${{ github.event.client_payload.branch }}
          path: changes

      - name: Install repo tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Set up Repo URL to use HTTPS
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"

      - name: Repo Init and Sync
        run: |
          mkdir -p workspace
          cd workspace
          echo "Initializing repo with manifest from https://github.com/jari-creator/manifest.git"
          repo init -u https://github.com/jari-creator/manifest.git -b main -m default.xml
          echo "Syncing repos"
          repo sync

      - name: Copy Changes to Correct Repository
        run: |
          repo_name=$(basename "${{ github.event.client_payload.repository }}" .git)
          target_dir="workspace/$repo_name"
          echo "Copying changes to $target_dir"

          if [ -d "$target_dir" ]; then
            cp -r changes/* "$target_dir/"
            echo "Changes copied successfully to $target_dir"
          else
            echo "Error: Target repository directory $target_dir does not exist."
            exit 1
          fi

      - name: Verify Changes in Workspace
        run: |
          echo "Contents of the target directory:"
          ls -al "workspace/$(basename "${{ github.event.client_payload.repository }}" .git)"
          repo_name=$(basename "${{ github.event.client_payload.repository }}" .git)
          target_dir="workspace/$repo_name"
          cd $target_dir
          cat init.txt
          
